### ISSUE TITLE
This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number)

### ISSUE THREAD

**Issue by satang456** [sman591/homebridge-lg-thinq-ac#76]
**LG Air Conditioner Model**
RAC_056905_WW

**Describe the bug**
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] device response.result.snapshot {
  'airState.windStrength': 6,
  'airState.wMode.lowHeating': 0,
  'airState.diagCode': 0,
  'airState.lightingState.displayControl': 0,
  'airState.wDir.hStep': 0,
  mid: 49971370,
  'airState.energy.onCurrent': 50,
  'airState.wMode.airClean': 0,
  'airState.quality.sensorMon': 0,
  'airState.miscFuncState.antiBugs': 0,
  'airState.tempState.target': 25,
  'airState.operation': 0,
  'airState.wMode.jet': 0,
  'airState.wDir.vStep': 100,
  timestamp: 1620207048605,
  'airState.powerSave.basic': 0,
  'airState.quality.PM10': 0,
  static: { deviceType: '401', countryCode: 'TH' },
  'airState.quality.overall': 0,
  'airState.tempState.current': 38,
  'airState.miscFuncState.extraOp': 0,
  'airState.reservation.sleepTime': 0,
  'airState.miscFuncState.autoDry': 0,
  'airState.reservation.targetTimeToStart': 0,
  meta: { allDeviceInfoUpdate: false, messageId: '9EblWN7KSFel0QNm2QGQAA' },
  'airState.quality.PM1': 0,
  'airState.quality.PM2': 0,
  online: true,
  'airState.opMode': 0,
  'airState.reservation.targetTimeToStop': 0,
  'airState.filterMngStates.maxTime': 0,
  'airState.filterMngStates.useTime': 0
}
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] ActiveCharacteristic: handleUpdatedSnapshot 0
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] SwingModeCharacteristic: handleUpdatedSnapshot 100
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] RotationSpeedCharacteristic: handleUpdatedSnapshot 6
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] CoolingThresholdCharacteristic: handleUpdatedSnapshot 25
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] HeatingThresholdCharacteristic: Target state is not "heat", ignoring snapshot update
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] HeatingThresholdCharacteristic: handleUpdatedSnapshot 25
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: handleUpdatedSnapshot 0
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] CurrentHeaterCoolerStateCharacteristic: handleUpdatedSnapshot 0
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] CurrentTemperatureCharacteristic: handleUpdatedSnapshot 38
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] FilterChangeCharacteristic: handleUpdatedSnapshot true
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] FilterLifeCharacteristic: handleUpdatedSnapshot NaN
[5/5/2021, 4:33:14 PM] [homebridge-lg-thinq-ac] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/5/2021, 4:33:14 PM] [homebridge-lg-thinq-ac] Error: 
    at FilterLifeLevel.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at FilterLifeLevel.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at FilterLifeLevel.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at FilterLifeCharacteristic.handleUpdatedSnapshot (/homebridge/node_modules/homebridge-lg-thinq-ac/src/characteristic/abstractCharacteristic.ts:71:20)
    at FilterLifeCharacteristic.handleUpdatedSnapshot (/homebridge/node_modules/homebridge-lg-thinq-ac/src/characteristic/filterLifeCharacteristic.ts:39:11)
    at LgAirConditionerPlatformAccessory.updateCharacteristics (/homebridge/node_modules/homebridge-lg-thinq-ac/src/platformAccessory.ts:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[5/5/2021, 4:33:14 PM] [LgThinqAirConditioner] Finished pushing updates to HomeKit

**Symptom check**
Accessories
* **Does your unit appear in the Home app?** 
* Show for the first time and disappeared later. Must be restarted Homebridge to display

**Comment by icces** [comment]
I have the exact same issue. Is there any solution?

**Comment by Arnwald** [comment]
Same here.

**Comment by sievideoexperts** [comment]
same here, i get it every minute. The control it self, works fine

**Comment by sman591** [comment]
Log error fixed in 22f0aa6007dc4ee993aed383e3c35afcc2707fd4, follow #94 for a fix for filter life being accurate
