### ISSUE TITLE
Please support "FQ17SADWEN"

### ISSUE THREAD

**Issue by Neoplanetz** [sman591/homebridge-lg-thinq-ac#79]
LG Air Conditioner Model
A/C Model : FQ17SADWEN
Homekit model : PAC_910604_WW

Describe the bug

Symptom check

Does your unit appear in the Home app? Yes
Is the current on/off state, temperature, and mode being reported? Yes
Does your unit respond to the controls? Yes

Relevant logs

[LgThinqAirConditioner] ActiveCharacteristic: handleUpdatedSnapshot 0
[LgThinqAirConditioner] SwingModeCharacteristic: handleUpdatedSnapshot undefined
[LgThinqAirConditioner] SwingModeCharacteristic: Error parsing state Error: Unsupported API value: undefined
[LgThinqAirConditioner] RotationSpeedCharacteristic: handleUpdatedSnapshot 2056
[homebridge-lg-thinq-ac] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 2056 exceeded maximum of 6. See https://git.io/JtMGR for more info.
[homebridge-lg-thinq-ac] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1950:16)
    at RotationSpeed.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at RotationSpeedCharacteristic.handleUpdatedSnapshot (/homebridge/node_modules/homebridge-lg-thinq-ac/src/characteristic/abstractCharacteristic.ts:71:20)
    at LgAirConditionerPlatformAccessory.updateCharacteristics (/homebridge/node_modules/homebridge-lg-thinq-ac/src/platformAccessory.ts:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[LgThinqAirConditioner] CoolingThresholdCharacteristic: Target state is not "cool", ignoring snapshot update
[LgThinqAirConditioner] CoolingThresholdCharacteristic: handleUpdatedSnapshot 26
[LgThinqAirConditioner] HeatingThresholdCharacteristic: handleUpdatedSnapshot 26
[LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: handleUpdatedSnapshot 1
[LgThinqAirConditioner] CurrentHeaterCoolerStateCharacteristic: handleUpdatedSnapshot 1
[LgThinqAirConditioner] CurrentTemperatureCharacteristic: handleUpdatedSnapshot 27
[LgThinqAirConditioner] FilterChangeCharacteristic: handleUpdatedSnapshot false
[LgThinqAirConditioner] FilterLifeCharacteristic: handleUpdatedSnapshot 40
[LgThinqAirConditioner] Finished pushing updates to HomeKit

**Comment by Neoplanetz** [comment]
appType: 'NUTS',
    modelCountryCode: 'WW',
    countryCode: 'KR',
    modelName: 'PAC_910604_WW',
    deviceType: 401,
    deviceCode: 'AI01',
    alias: 'Stand Aircon',
    deviceId: 'a06f11d1-d324-1fee-****-402f86a3fd1b',
    fwVer: '',
    imageFileName: 'ac_home_stand_airconditioner_img.png',
    ssid: 'N*********',
    softapId: '',
    softapPass: '',
    macAddress: '',
    networkType: '02',
    timezoneCode: 'Asia/Seoul',
    timezoneCodeAlias: 'Korea/Seoul',
    utcOffset: 9,
    utcOffsetDisplay: '+09:00',
    dstOffset: 9,
    dstOffsetDisplay: '+09:00',
    curOffset: 9,
    curOffsetDisplay: '+09:00',
    sdsGuide: '{"deviceCode":"AI01"}',
    newRegYn: 'N',
    remoteControlType: '',
    userNo: 'KR2105131523567',
    tftYn: 'N',
    deviceState: 'E',
    snapshot: {
      'airState.windStrength': 2056,
      'airState.aroma.color': 0,
      'airState.diagCode': 0,
      'airState.quality.odor': 0,
      'airState.humidity.current': 79,
      'airState.voice.feedbackSound': 1,
      'airState.operation': 0,
      'airState.wMode.flowLongPower': 0,
      'airState.wDir.upDown': 0,
      'airState.quality.PM10': 10,
      static: [Object],
      'airState.lightingState.magicBrightness': 2,
      'airState.quality.overall': 1,
      'airState.tempState.current': 27,
      'airState.wDir.right': 0,
      'airState.voice.QVoiceOption': 0,
      'airState.reservation.targetTimeToStart': 0,
      meta: [Object],
      'airState.wMode.humanCare': 0,
      'airState.wMode.smartCare': 0,
      'airState.reservation.targetTimeToStop': 0,
      'airState.voice.volume': 3,
      'airState.smartCare.status': 0,
      'airState.lightingState.displayControl': 0,
      mid: 14206933,
      'airState.aroma.state': 0,
      'airState.miscFuncState.watertankLight': 0,
      'airState.energy.onCurrent': 0,
      'airState.voice.sensitivity': 0,
      'airState.wMode.airClean': 0,
      'airState.lightingState.signal': 1,
      'airState.quality.sensorMon': 1,
      'airState.aroma.sound': 0,
      'airState.lightingState.magicColor': 0,
      'airState.tempState.target': 26,
      'airState.wMode.jet': 0,
      timestamp: 1621090344851,
      'airState.powerSave.basic': 0,
      'airState.wDir.leftRight': 0,
      'airState.wMode.iceValley': 0,
      'airState.wMode.flowForest': 0,
      'airState.wMode.flowShower': 0,
      'airState.reservation.sleepTime': 0,
      'airState.voice.recog': 0,
      'airState.miscFuncState.autoDry': 1,
      'airState.wDir.left': 0,
      'airState.quality.PM1': 8,
      'airState.quality.PM2': 8,
      online: true,
      'airState.opMode': 1,
      'airState.filterMngStates.maxTime': 720,
      'airState.filterMngStates.useTime': 429
    },
    online: true,
    platformType: 'thinq2',
    area: 2332304,
    regDt: 20210515123313,
    blackboxYn: 'Y',
    modelProtocol: 'STANDARD',
    receipeVersion: 0,
    activeSaving: 'OFF',
    smartCareV2: 'OFF',
    order: 0,
    nlpAlias: 'none',
    drServiceYn: 'N',
    fwInfoList: [ [Object], [Object], [Object] ],
    regDtUtc: '20210515033313',
    regIndex: 0,
    groupableYn: 'Y',
    controllableYn: 'Y',
    combinedProductYn: 'N',
    masterYn: 'Y',
    initDevice: false,
    firebaseLogKey: 'P:D',
    tclcount: 0
  }

**Comment by Neoplanetz** [comment]
what is 'airState.wDir.vStep' ? in my case, my model snapshot excluded  'airState.wDir.vStep'

**Comment by sman591** [comment]
Interesting, it looks like your unit uses `wDir` values of upDown/left/leftRight instead of vStep for this.

**Comment by sman591** [comment]
windStrength is also super high... 2056

What features **do** work for your unit?
